name: Type Check

on:
  push:
    branches: [ main ]
    paths: 
      - 'src/**/*.ts'
      - 'src/**/*.tsx'
      - 'tsconfig.json'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main ]
    paths: 
      - 'src/**/*.ts'
      - 'src/**/*.tsx'
      - 'tsconfig.json'
      - 'package.json'
      - 'package-lock.json'

jobs:
  typecheck:
    name: TypeScript Type Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run TypeScript type check
      run: npx tsc --noEmit